export const CONTACT_COPY = {
  title: "Send a note",
  nameLabel: "Your name",
  messageLabel: "Message",
  emailLabel: "Email",
  namePlaceholder: "What should I call you?",
  messagePlaceholder: "Tell me what you want to build...",
  emailPlaceholder: "you@email.com",
  contactHelper: "Now add your name and email.",
  nextLabel: "Next",
  sendLabel: "Send",
  sendingLabel: "Sending",
  sentLabel: "Sent",
  errorLabel: "Try again",
  backLabel: "Back",
  closeLabel: "Cancel",
  successTitle: "Message sent",
  successMessage: "I got it. I will reply soon.",
  errorMessage: "Could not send yet. Try again in a bit.",
} as const;
